### PR TITLE
Fix NPE when getting error message and add HTTP response information

### LINKED ISSUE #3: NPE when publishing to an incorrect URL
I was testing the publication of a plugin created with the command `nextflow plugin create` . It configures the registry to `https://nf-plugins-registry.dev-tower.net/api`, which doesn't exist. The command `./gradlew releasePlugin` returns the following NPE instead of an error.

```
Caused by: java.lang.NullPointerException: Cannot invoke "io.nextflow.gradle.registry.RegistryClient$ErrorResponse.getType()" because "err" is null
        at io.nextflow.gradle.registry.RegistryClient.publish(RegistryClient.groovy:37)
        at io.nextflow.gradle.registry.RegistryUploadTask.run(RegistryUploadTask.groovy:34)
```

### PR DESCRIPTION
**Pull request by jorgee**
close #3 
The current implementation assumes the request will return an HTTP response with an `ErrorResponse` serialized as JSON, but this only happens when the publish registry URL is correct. In other cases, the error response is null or throws a JSONParseException, hiding the real reason for the error.

This PR fixes this incorrect behaviour by checking the response content.
- If content matches with ErrorResponse, the message includes HTTP code, error type, and message
- If content doesn't match with ErrorResponse, the message includes the HTTP code and the content string
- If there is no content, it just returns the HTTP code

### CODE REVIEW

File: src/main/groovy/io/nextflow/gradle/registry/RegistryClient.groovy [hunk 1]
```diff
@@ -33,14 +38,31 @@ class RegistryClient {
              def rep = http.execute(req)) {
 
             if (rep.statusLine.statusCode != 200) {
-                def err = gson.fromJson(new InputStreamReader(rep.entity.content), ErrorResponse)
-                throw new RuntimeException("Failed to publish plugin: ${err.type} - ${err.message}")
+                throw new RuntimeException(getErrorMessage(rep))
```
Comment (pditommaso) [inline src/main/groovy/io/nextflow/gradle/registry/RegistryClient.groovy:41]: Not sure how much it's worth mapping the response to the ErrorResponse, there are entire classes of non-200 status that are not errors (2xx and 3xx) also 5xx error could have their own error format. 

I would create a custom exception adding the response text as an additional details in the error message as it is (without paring it)

**Review by pditommaso — APPROVED** [review]
